vim.filetype.add({
	filename = {
		[".gitignore"] = "conf",
		["kitty.conf"] = "bash",
		[".env"] = "bash",
		["Deskfile"] = "bash",
		["tool-versions"] = "conf",
		[".tool-versions"] = "conf",
		["default-python-packages"] = "conf",
		["default-node-packages"] = "conf",
		["default-gems"] = "conf",
		["tsconfig.json"] = "jsonc",
		[".prettierrc"] = "jsonc",
		[".eslintrc"] = "jsonc",
		["Brewfile"] = "ruby",
		["Brewfile.mas"] = "ruby",
		["Brewfile.cask"] = "ruby",
		["NEOGIT_COMMIT_EDITMSG"] = "NeogitCommitMessage",
	},
	extension = {
		puml = "plantuml",
		json = "jsonc",
		kitty = "bash",
		eslintrc = "jsonc",
		prettierrc = "jsonc",
		conf = "conf",
		mdx = "markdown",
		md = "markdown",
		lexs = "elixir",
		exs = "elixir",
		eex = "eelixir",
		keymap = "keymap",
		cts = "typescript",
		mts = "typescript",
		zsh = "zsh",
	},
})
